credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: 'abc' # Will be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: 'def' # Will be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
