"""Add chat sessions and messages

Revision ID: 666e27b9bb2f
Revises: a1b2c3d4e5f6
Create Date: 2026-03-13 19:51:08.042500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666e27b9bb2f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=True),
    sa.Column('firebase_display_name', sa.VARCHAR(), nullable=True),
    sa.Column('profile_picture_url', sa.VARCHAR(), nullable=True),
    sa.Column('firebase_photo_url', sa.VARCHAR(), nullable=True),
    sa.Column('use_alias_as_display', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=1)
    # ### end Alembic commands ###

