"""Create insights table

Revision ID: eb5f0e811faa
Revises: 
Create Date: 2025-11-18 23:04:39.297661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5f0e811faa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.String(), nullable=False),  # Changed from UUID to String for SQLite compatibility
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chat_session_id', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('tickers', sa.JSON(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_chat_session_id'), 'insights', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_chat_session_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###

